alert:
  file: D://Report//alert-plot.csv
cron:
  expression: 0 0/1 * * * ?
crop:
  types: food,cash,drug
irrigation:
  file: D://Report//auto-irrigation-plot.csv
logging:
  file:
   name: D://Report//AutoIrrigation-App.log
retry:
  exceed: 3


spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    ucp:
      connection-factory-class-name: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:h2:mem:testdb
    db_url: jdbc:h2:mem:testdb
    username: sa
    password: 
   
    
    
server:
  port: 8080
  servlet:
    context-path: /irrigation
