alert:
  file: D://Report//alert-plot.csv
cron:
  expression: 0 0/30 * * * ?
crop:
  types: food,cash,drug
irrigation:
  file: D://Report//auto-irrigation-plot.csv
logging:
  file:
   name: D://Report//AutoIrrigation-App.log
retry:
  exceed: 3


spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
#   hibernate:
#      ddl-auto: create
  datasource:
    ucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
    url: jdbc:oracle:thin:@localhost:1521/xe
    db_url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: system
   
    
    
server:
  port: 8080
  servlet:
    context-path: /irrigation
